### ISSUE TITLE
Problem with composer autoload

### ISSUE THREAD

**Issue by study64** [aVadim483/fast-excel-reader#1]
Hi, I think you have a problem with your composer settings. I have installed your library (with composer) on my project and I get this error:

Class 'avadim\FastExcelReader\Excel' not found

when I use it. I tried with and without "\\" but nothing change. I saw your composer json and in the line 21 you have this line:

"avadim\\FastExcelWriter\\": "./src/FastExcelReader"

and it said Writer instead of Reader but I changed that and issue still there.

**Comment by aVadim483** [comment]
Fixed https://github.com/aVadim483/fast-excel-reader/releases/tag/v1.3.2
