### ISSUE TITLE
Inconsistency on formatCode per numFmtId

### ISSUE THREAD

**Issue by AzzaAzza69** [aVadim483/fast-excel-reader#11]
Hi,
Some of the format patterns for 14 - 22 appear to be locale/short date/long date combinations as my Excel show these values:
```
14=>dd/mm/yyyy  (my windows short date format)
15=>dd-mmm-yy
16=>dd-mmm
17=>mmm-yy
18=>h:mm
19=>h:mm AM/PM
20=>h:mm:ss AM/PM
21=>hh:mm
22=>hh:mm:ss
```

**Comment by aVadim483** [comment]
Yes, I know that the date format can be locale dependent, so the library returns the date value as a timestamp, allowing you to format it yourself. I'm sure that value is more important to import than format. The format is used to determine that a cell value contains a date value

**Comment by AzzaAzza69** [comment]
Sometimes value is as important as format for us.  We have spreadsheets which we process and extract out half (data and format) and write these out along with some new fields to a new file (so I need to be able to duplicate the source value + pattern)...

**Comment by aVadim483** [comment]
Well, I think you need something like this:
```php
$result = [];
$sheet = $excel->sheet();
foreach ($sheet->nextRow([], null, true) as $rowNum => $rowData) {
    foreach ($rowData as $col => $cellData) {
        $value = $cellData['v'];
        $styleIdx = $cellData['s'];

        $styles = $excel->getCompleteStyleByIdx($styleIdx, true);

        // it's a numFmtId from XLSX-file
        $formatNumId = $styles['format-num-id'];

        // get Excel pattern of the cell
        $excelFormat = $excel->getFormatPattern($styleIdx);

        // get format converted for use in php functions date(), gmdate(), etc
        $phpFormat = $excel->getDateFormatPattern($styleIdx);

        // here you analyze the data and write the result you need
    }
}
```

**Comment by aVadim483** [comment]
In v2.10.0 was improved auto-detection of date/time patterns for numFmtId 14 (Short date), 20 (Short time), 21 (Long time), 22 (Date-time)
