### ISSUE TITLE
Is there an easy/memory efficient way to read from a file, add column/s and write to a new file?

### ISSUE THREAD

**Issue by AzzaAzza69** [aVadim483/fast-excel-reader#13]
So in essence the user thinks that the target file is their source file with some extra columns added?
Their files will have values, styles, formatting, column widths and row heights...

**Comment by aVadim483** [comment]
You can try to do this using the following libraries
https://github.com/aVadim483/fast-excel-reader
https://github.com/aVadim483/fast-excel-writer

but a lot depends on the specific details of your task

**Comment by sprain** [comment]
@aVadim483 Can a reader Excel instance be turned into a writer Excel instance? If not, would you accept a PR allowing to do so?

**Comment by aVadim483** [comment]
> @aVadim483 Can a reader Excel instance be turned into a writer Excel instance? If not, would you accept a PR allowing to do so?

I do not think it's a good idea. The library is designed for the fastest possible reading. Adding recording functionality to it may impact performance. A new library for working with Excel templates will be released soon https://github.com/aVadim483/fast-excel-templator

**Comment by sprain** [comment]
My use case would be to append data to an existing excel. So yeah, looks like `FastExcelTemplator` could be of use there. Let me know if I can help somehow.
