### ISSUE TITLE
Deprecated php8.1 function call

### ISSUE THREAD

**Issue by gearoidc** [aVadim483/fast-excel-reader#15]
Function strftime() is deprecatedPHP message: [/var/www/vhosts/biome/vendor/avadim/fast-excel-reader/src/FastExcelReader/Excel.php:124

Changing **strftime** to **date** fixes the issue

**Comment by aVadim483** [comment]
This is strange because in PHP 8.1 the IntlDateFormatter class must be defined, and if it is defined, then the strftime() function is not used

**Comment by aVadim483** [comment]
I think your PHP extension ```intl``` is not allowed
The problem is that the ```date()``` function does not always give the desired result

**Comment by aVadim483** [comment]
in v.2.14 strftime() is no longer used and ext-intl required for IntlDateFormatter
