### ISSUE TITLE
Get all cells in text format

### ISSUE THREAD

**Issue by vdussan** [aVadim483/fast-excel-reader#20]
Currently when using the $sheet->readRows() method;

This returns the contents of the cells converted to integers, I need to get the cells in text format.

**Comment by aVadim483** [comment]
```php
$result = [];
$sheet->readCallback(function ($row, $col, $val) use(&$result) {
    $result[$row][$col] = (string)$val;
});
var_dump($result);
```

**Comment by darmadiff** [comment]
I try this method, but when I fill cell with leading zero then it will be eliminated. Something like 043435543 will be 43435543.
