### ISSUE TITLE
Check if worksheet is visible or hidden

### ISSUE THREAD

**Issue by BlackbitDevs** [aVadim483/fast-excel-reader#23]
Currently it is possible to check if a worksheet is active but I did not find a way to determine if it is hidden. 
I don't know if this helps but PhpSpreadsheet gets this information from the field `state`, see https://github.com/PHPOffice/PhpSpreadsheet/blob/1c77e0049902b245c92c233aadcc834f50d246af/src/PhpSpreadsheet/Reader/Xlsx.php#L786

**Comment by aVadim483** [comment]
in version v.2.18 functions isHidden() and isVisible() were added

**Comment by BlackbitDevs** [comment]
Works like a charm, thanks!
