### ISSUE TITLE
Merged cells

### ISSUE THREAD

**Issue by Jan-Walther-Basilicom** [aVadim483/fast-excel-reader#28]
Is there a way to support merged cells? In this case all columns within the merge range should return the same value. Currently only the first column in the merge range has the value, the other ones have `""`.

**Comment by aVadim483** [comment]
When you merge cells, Excel actually writes the value to only the first one. That's why you get this result

**Comment by Jan-Walther-Basilicom** [comment]
Ok, but is it possible to detect if a cell is merged with another one?

**Comment by aVadim483** [comment]
And you can use:

* Sheet::getMergedCells() -- Returns all merged ranges
* Sheet::isMerged(string $cellAddress) -- Checks if a cell is merged
* Sheet::mergedRange(string $cellAddress) -- Returns merge range of specified cell

**Comment by aVadim483** [comment]
For example
```php
if ($sheet->isMerged('B3')) {
    $range = $sheet->mergedRange('B3');
}
```
