### ISSUE TITLE
Skipping empty rows

### ISSUE THREAD

**Issue by PaulCombal** [aVadim483/fast-excel-reader#29]
Hello,

Is it planned to have a feature to skip reading empty rows entierly? Sometimes it reads empty rows with empty strings or such.

PhpSpreadsheets does a good job with that, for example:
```php
if ($row->isEmpty(
    CellIterator::TREAT_EMPTY_STRING_AS_EMPTY_CELL | 
    CellIterator::TREAT_NULL_VALUE_AS_EMPTY_CELL)
    ) { // Ignore empty rows
    continue;
}
```

I think if would be very nice to have an equivalent. I can imagine something like:
```php
$row = $sheet->readNextRow(Excel::ROW_NOT_EMPTY | Excel::TREAT_EMPTY_STRING_AS_EMPTY_CELL ....)
```

As of right now we can implement in our codebase it afterwards but it feels a bit awkward.

Thank you

**Comment by aVadim483** [comment]
My library already skips empty cells and empty rows by default. There are no NULL values ​​in cells, so it will be enough to add only the constant like TREAT_EMPTY_STRING_AS_EMPTY_CELL and you will get the result you need.

Well, I will add this feature

**Comment by aVadim483** [comment]
https://github.com/aVadim483/fast-excel-reader?tab=readme-ov-file#empty-cells--rows

**Comment by PaulCombal** [comment]
That's just amazing.. we'll try it right away! Many thanks for everything!
