### ISSUE TITLE
php8.1 deprecation issue

### ISSUE THREAD

**Issue by DaanBaars** [aVadim483/fast-excel-reader#3]
Deprecated: Function strftime() is deprecated in vendor/avadim/fast-excel-writer/src/FastExcelWriter/Excel.php on line 167
Deprecated: Function strftime() is deprecated in vendor/avadim/fast-excel-writer/src/FastExcelWriter/Excel.php on line 168

**Comment by aVadim483** [comment]
It seems this is about other package - https://github.com/aVadim483/fast-excel-writer
It have fixed in v2.3.9
