### ISSUE TITLE
Problem with certain xlsx file

### ISSUE THREAD

**Issue by Playys228** [aVadim483/fast-excel-reader#30]
Can't read this xlsx file.

XMLReader::open(zip:///app/storage/supplierPricelistFiles/spl_591_manual_2024-10-24_14-21-02_problemFile1.xlsx#xl/sharedStrings.xml): Failed to open stream: operation failed in /app/vendor/avadim/fast-excel-reader/src/FastExcelReader/Reader.php:110

[problemFile(1).xlsx](https://github.com/user-attachments/files/17506027/problemFile.1.xlsx)

**Comment by aVadim483** [comment]
I see, I'll fix it

**Comment by aVadim483** [comment]
fixed

**Comment by Playys228** [comment]
thx
