### ISSUE TITLE
Error reading col Y

### ISSUE THREAD

**Issue by jeroendhvv** [aVadim483/fast-excel-reader#5]
The library skips reading column Y. 
When the colNum is looked up (line 298 of Excel.php)
if ($letters > 'XFD') {
   return self::EXCEL_2007_MAX_COL;
}
'Y' > 'XYD' yields TRUE (in php 7.4)
Also when the index gets added to the $colIndex it is already limited to EXCEL_2007_MAX_COL (line 306);

**Comment by aVadim483** [comment]
fixed
