### ISSUE TITLE
Add Image / drawing supports

### ISSUE THREAD

**Issue by faustfizz** [aVadim483/fast-excel-reader#6]
This library is so awesome and useful.

But I would like to have the ability to import images from xlsx files

You see, people use xlsx for customer registration, when you want to make an application for customer registration many do not accept because they think they can never migrate their data which seems logical.

With this tool, it is possible to migrate from xlsx to sql but what about images?

So I would like if possible to have this feature or someone to tell me how I can integrate it.

Thanks in advance

**Comment by aVadim483** [comment]
Hi! I think I can do it in the new version

**Comment by faustfizz** [comment]
I'll be happy twice 😊
Thanks in advance

**Comment by aVadim483** [comment]
https://github.com/aVadim483/fast-excel-reader#images-functions

**Comment by faustfizz** [comment]
> https://github.com/aVadim483/fast-excel-reader#images-functions

@aVadim483 
Thanks you!
You are genius. I haven't tested it yet but I'll do it soon.
When I use KEYS_FIRST_ROW, how to get image the current row (I didn't see it on readMe)? 
You are the best 👌

**Comment by aVadim483** [comment]
```php
$excel = Excel::open($file);
$sheet = $excel->sheet();
foreach ($sheet->nextRow() as $rowNum => $rowData) {
    // getImageListByRow() without argument returns images info from current row as array
    $imageList = $sheet->getImageListByRow();
    foreach ($imageList as $imageInfo) {
        // $imageInfo['address'] contains cell address of an image
        $imageBlob = $sheet->getImageBlob($imageInfo['address']);
    }
}
```
