### ISSUE TITLE
Doesn't work with a lot of xlsx files

### ISSUE THREAD

**Issue by fabiochelly** [aVadim483/fast-excel-reader#8]
I tried to replace phpspreadsheet with fast-excel-reader to convert some files to  CSV.
But a lot of files sent by my clients can't be read with this lib. This one for instance (see attached file).

No exception, readRows return an empty array and $sheet->nextRow() doesn't work either.

[Feuille de calcul sans titre (40).xlsx](https://github.com/aVadim483/fast-excel-reader/files/11650869/Feuille.de.calcul.sans.titre.40.xlsx)

**Comment by aVadim483** [comment]
It seems that this file was not created using Microsoft Excel, but I will see how I can solve this problem

**Comment by aVadim483** [comment]
Well, I've resolved this problem in v.2.1.1 and the test passed successfully with you file

**Comment by fabiochelly** [comment]
OK, it works fine now for these kind of file.

By the way I noticed something: when the xlsx file path supplied is wrong (file is missing for instance), it provokes a fatal error. In your Reader.php, it seems that you test if ($zip->open()) { }
But you're supposed to check: $zip->open(...) === true (with a strict comparison).
Because $zip->open() can return an error code (int) that can be interpreted as true

It's not a big problem but when the path is wrong, we get a Fatal error instead of an exception.

**Comment by fabiochelly** [comment]
When I look at the code, it seems that you test if ($zip->open()) as a bool.
But you're supposed to check: $zip->open(...) === true

Because open can returns an error code that can be interpreted as true

**Comment by aVadim483** [comment]
yep, you're right, I'll add error handling here

**Comment by aVadim483** [comment]
done
